### ISSUE TITLE
showing pause icon on camera

### ISSUE THREAD

**Issue by citayesh** [mozmorris/react-webcam#338]
![b162cfba-66be-4692-be10-d9a4ef4879e1](https://user-images.githubusercontent.com/50526777/155143089-82f3e4ad-2660-4628-9aba-3663ad0d72ec.png)
i opned the camera to take picture and it happend

**Comment by nschucky** [comment]
You could try setting the controls to false
```
<Webcam
  ...
  controls={false}
/>
```

**Comment by Nikkolas-Cage** [comment]
you can put a 

`
<Webcam
   ....
   poster="blankimage.jpg"/>
`

**Comment by chen-rn** [comment]
I think [this solved issue](https://github.com/mozmorris/react-webcam/issues/318) may be discussing a similar issue. Though I'm unable to reproduce the solution.

Basically, before camera permission is granted, the "empty" video player shows a "Play Button". Once permission is granted, the "Play Button" turns into a "Pause" button momentarily before vanishing from existence.

This seems to only happen on iOS.
@mozmorris any ideas on how to fix this?

**Comment by frankgalindo** [comment]
I had the same issue and found a solution using CSS.

```css
video::-webkit-media-controls-panel {
	display: none !important;
	-webkit-appearance: none;
}

video::-webkit-media-controls-play-button {
	display: none !important;
	-webkit-appearance: none;
}

video::-webkit-media-controls-start-playback-button {
	display: none !important;
	-webkit-appearance: none;
}
```
Another way to fix using CSS is to disable pointer events on the video element:

```css
video {
  pointer-events: none;
}
```
